### ISSUE TITLE
Please can you add this news item on OpenHW website on March 9th morning (CET time)

### ISSUE THREAD

**Issue by NaylDSouza** [openhwgroup/openhwgroup.org#291] opened 2021-03-08 17:42 UTC
//Please can we add this as a news item on the OpenHW website by morning of March 9th 
https://www.openhwgroup.org/news/

I can personally add this separately to the Eclipse news upload site tomorrow.

Image to be included too//

 
Headline: 
**OpenHW Group and Mitacs announce OpenHW Accelerate – $22.5M research program to stimulate architecture research for next generation of open-source processors

Today, OpenHW Group and Mitacs announced OpenHW Accelerate, a $22.5M multi-year co-funded research program, the world’s first open-source hardware research program of its kind. OpenHW Accelerate will drive research in next generation of class-leading open-source processors, architectures and support software for embedded AI and machine learning (ML) applications, among other future energy-intensive computing requirements.  

OpenHW Group, the global not-for-profit organization set up to facilitate collaboration in the design and development of open-source cores, related IP and software tools, teamed up with Mitacs, a not-for-profit organization supporting research within Canadian and International academic institutions to create the innovative OpenHW Accelerate program. 
 
Rick O’Connor, Founder and CEO at OpenHW Group, said: “OpenHW Group is transforming how the industry adopts open-source hardware and is bringing relevant research projects to leading industry and academic institutions worldwide. With strong support from Mitacs, the OpenHW Accelerate co-funded research project is available to all members and technology partners across the OpenHW ecosystem worldwide.”

The first OpenHW Accelerate project, CORE-V VEC, is a research effort to explore architectural optimizations for RISC-V vector processor implementations used in high-throughput multidimensional sensor data processing and ML acceleration at the Edge. 

According to Dr. John Hepburn, Mitacs CEO and Scientific Director: “The OpenHW Accelerate program, supported by the Government of Canada represents a major step forward in open-source hardware research. This collaboration marks the onset of first-of-its kind, openly-available hardware research to those around the globe; this accessibility reduces barriers for start-ups and small businesses to advance.”

The OpenHW Group and Mitacs plan to announce several new OpenHW Accelerate projects pairing industrial sponsors with academic institutions in the coming months.

With industry sponsorship from CMC Microsystems, Canada’s leading specialists in microsystems and nanotechnologies, CORE-V VEC is a three-year, joint-research collaboration between Polytechnique Montréal and ETH Zürich, institutions at the forefront of international semiconductor and software engineering research.

Gordon Harling, President and CEO of CMC Microsystems, added: “The potential of open-source hardware is boundless. As the industrial sponsor for the CORE-V VEC project, this is a perfect fit for CMC to connect research innovation with industrial applications like AI and machine learning where Canada is recognized as a global leader, and is well-positioned for future growth.”

More details about the OpenHW Accelerate program and CORE-V VEC will be presented via an OpenHW TV webinar on March 18 featuring officials from all of the project’s collaborating organizations. Register via https://bit.ly/3dMIay3.

![OpenHW-Accelerate-press-image](https://user-images.githubusercontent.com/74318457/110359333-48ec4d80-8035-11eb-92c3-9fd468f484c1.jpg)

**Comment by flora8984461** [comment] 2021-03-08 21:36
Hi @NaylDSouza 
I have adjusted a little bit of Headline and subtitle since it's too crowded to put the long title all in "headline".

Please check the preview: https://deploy-preview-292--eclipsefdn-openhwgroup.netlify.app/news/2021/03/09/openhw-group-and-mitacs-announce-openhw-accelerate/

**Comment by flora8984461** [comment] 2021-03-09 12:56
Hi @NaylDSouza The site is merged live and please check: https://www.openhwgroup.org/news/2021/03/09/openhw-group-and-mitacs-announce-openhw-accelerate/

**Comment by rickoco** [comment] 2021-03-09 14:22
@flora8984461 @ericpoirier - the page is live on the site, but it does not show up in the News items on the home page or in the “See All News” summary page.

**Comment by flora8984461** [comment] 2021-03-09 14:34
@rickoco @NaylDSouza Hi, I just poke into the newsroom, it appears that you forgot to set it as published. 

![image](https://user-images.githubusercontent.com/39588094/110486337-8e069300-80ba-11eb-9b0d-f61b8706289d.png)

I just set it to published, and it should show up soon, thanks!

**Comment by flora8984461** [comment] 2021-03-09 14:41
@rickoco @NaylDSouza Please check https://www.openhwgroup.org/news/, it is showing now. Thx!

**Comment by chrisguindon** [comment] 2021-03-09 16:32
The issue is that we have a well-defined process for all our websites but we made an exception for OpenHWGroup.

I thinking this process would be simplified if you would work directly with the news team and the news team would work with us to create the page.

**Comment by NaylDSouza** [comment] 2021-03-09 16:44
Ok @chrisguindon, that sounds like a plan. Please let me know the next steps. I've directly emailed Jacob Harris in the past for support, or perhaps there is another member of the team I can work with directly, or did you want me to simply use the News Upload on Eclipse (via https://newsroom.eclipse.org/node/add/news) to add news stories with a note in bold to ensure that the www.OpenHWGroup.org/news URL is used?

**Comment by chrisguindon** [comment] 2021-03-09 17:15
Yes,

Jacob is our moderator for the newsroom website. It might make sense for you to work with him directly for news items instead of us.

Let me discuss this with Shanda tomorrow and we will post an update.

**Comment by shanda-eclipse** [comment] 2021-03-11 13:18
Hi guys,

@chrisguindon and I have discussed, and we think the best option would be for you to email your request to news@eclipse.org. From there the marketing team will create the bug (on https://github.com/openhwgroup/openhwgroup.org/issues) and post the article to the newsroom. This will allow our team to manage the schedule.

What we need from you:

- Article title/headline
- Article summary (we can pull this from the article, but if you have something specific please sent it)
- Article body
- Publishing date and time
- Where it should be published (openhwgroup.org and/or eclipse.org)

Please provide the content at least 2 business days ahead of publishing so we can ensure we meet your timelines.

Thanks.

**Comment by flora8984461** [comment] 2021-03-12 17:59
The news item is live, closing

**Closed by flora8984461** 2021-03-12 17:59 UTC
