### ISSUE TITLE
Redirect WhaleMicro's logo to company URL

### ISSUE THREAD

**Issue by ZahraFazli** [openhwgroup/openhwgroup.org#496] opened 2022-08-24 13:43 UTC
Currently, WhaleMicroelectronics' logo is being redirected to OpenHW Group website. Please add the company's URL (http://www.whalemicro.com) to the logo.

**Comment by ZacharySabourin** [comment] 2022-08-24 17:18
@ZahraFazli The preview of the requested change is available here: https://deploy-preview-499--eclipsefdn-openhwgroup.netlify.app/ :)

**Comment by ZahraFazli** [comment] 2022-08-24 18:07
+1 Thanks

**Comment by ZahraFazli** [comment] 2022-08-24 18:12
Hi, can you please update this page as well: https://www.openhwgroup.org/membership/members/
Thanks

**Comment by autumnfound** [comment] 2022-08-24 18:27
The changes are not live yet. Once we get +1, someone needs to go merge in the changes which can take a few hours depending on the persons workload.

**Comment by autumnfound** [comment] 2022-08-24 18:31
I've merged in the changes so they should be live in the next 5 minutes. Please be sure to check the preview for functionality and not production when confirming a change set or whether a change was missed. That is the most reliable way before the issue is closed/merged, or when you are unsure if changes are live yet.

**Comment by ZahraFazli** [comment] 2022-08-24 19:38
thanks. it works!

**Comment by autumnfound** [comment] 2022-08-24 20:12
Glad we could help! Closing the issue as its complete

**Closed by autumnfound** 2022-08-24 20:12 UTC
