### ISSUE TITLE
calendar does not consistently display

### ISSUE THREAD

**Issue by DBees** [openhwgroup/openhwgroup.org#318] opened 2021-05-24 01:46 UTC
**Describe the bug**
Calendar at the working groups page is sometimes not visible.

Following report from dhua@futurewei.com
"i did an experiment, for my company's windows 10 laptop, I can not see the calendar for both Chrome and Microsoft Edge.  In my personal Windows 10 laptop, I can see it in Edge browser but not in Chrome. "

From myself:
Sometimes the calendar is not visible from Chrome browser on windows 10 laptop (but usually it is visible)

**Comment by linkfang** [comment] 2021-05-27 21:13
Hi @DBees , 

We tested on multiple different Windows 10 laptops (also including Linux one) but could not reproduce the issue on both Chrome and Edge.

Could you provide some more info on the situations when the calendar is not visible? Like did you set up some specific settings to reproduce it? Or did this only happen in some certain time period? When this happened, could you access any Google services?

This kind of information could help a lot on figuring out the root cause, and the more info the better. 😂

Thanks!

**Comment by linkfang** [comment] 2021-10-15 19:38
OK, I will keep an eye on this, haven't met this situation yet.

Let me re-phrase the issue. You have been using the same laptop, browser (Chrome) and Internet/WIFI, and sometimes/occasionally, the calendar won't show up. 
How do you normally solve the issue, like refresh the page or just wait for a moment/a few hours?

And it would be great if you could do a screen shot next time when you encounter this. So, I can at least see what's happening on the page. 

Thanks!

**Comment by DBees** [comment] 2021-10-15 22:19
Yes I will do a screen shot next time I notice this!

What I see is the rest of the web page rendering, but the calendar appears blank.

Refreshing the page doesn’t do it, but if I wait a few hours and try again it may be back.

Thank you!

Duncan

**Comment by ericpoirier** [comment] 2022-01-12 18:29
Closing this issue. Please re-open if the problem comes back.

Thanks.

**Closed by ericpoirier** 2022-01-12 18:29 UTC
